name: Run Tests (Main)

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with: 
          node-version: 24
      - run: npm install && cd client && npm install && cd ..
      - run: npm run test:frontend
      - run: npm run test:backend


