name: Run Tests (Other)

on: 
  pull_request:
    branches-ignore:
      - main
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - run: npm install && cd client && npm install && cd ..
      - run: npm run test

